### ISSUE TITLE
Feedback Request:NTW-05 IP-addressing

### ISSUE THREAD

**Issue by Ephraim52** [Techgrounds-Cloud-9/cloud-9-Ephraim52#6]
**Feedback Request NTW-05 IP addressing**
Permalink to file: [https://github.com/Techgrounds-Cloud-9/cloud-9-Ephraim52/blob/dea0ab56904e7d216346750343224252c1be8c3f/04_Network_01/NTW-05/NTW-05%20IP-addressing.md]

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by yourlocaldaphne** [comment]
**Summary**
- Does the summary describe the subject matter fully?
Yes
- Is the summary written in own words?
Yes
- Is there crucial information missing in the summary?
No
- Is the description clear enough?
Yes

**Key Terminology**
- Are there missing key terms?
No, there a lot of good key terms.
- Are the key terms explained well?
Yes, very wel explained.

**Sources**
- Are the sources mentioned?
Yes
- Are the mentioned sources correct?
Yes

**Excercise**
(Where applicable)
- Is the result correct?
Yes, with very helpful screenshots .
- Are the experienced problems and solutions described well?
Yes, no challanges were faced.

**Comment by jairvaneer** [comment]
**Summary**
- Does the summary describe the subject matter fully?
- Yes
- Is the summary written in own words?
- Yes
- Is there crucial information missing in the summary?
- No
- Is the description clear enough?
- Yes

**Key Terminology**
- Are there missing key terms?
- No
- Are the key terms explained well?
- Yes

**Sources**
- Are the sources mentioned?
- Yes
- Are the mentioned sources correct?
- Yes

**Excercise**
(Where applicable)
- Is the result correct?
- Yes
- Are the experienced problems and solutions described well?
- Yes
