### ISSUE TITLE
Feedback Request:

### ISSUE THREAD

**Issue by Ephraim52** [Techgrounds-Cloud-9/cloud-9-Ephraim52#7]
**Feedback Request [Sec-08 Detection, response and analysis]**
Permalink to file: [https://github.com/Techgrounds-Cloud-9/cloud-9-Ephraim52/blob/dc27b0a84a6fd02404c06817d22285b722b3156f/05_Security_1/Sec-08/Sec-08%20%20Detection,%20response%20and%20analysis.md]

Template for peers for review: 
```
**Summary**
- Does the summary describe the subject matter fully?
- Is the summary written in own words?
- Is there crucial information missing in the summary?
- Is the description clear enough?

**Key Terminology**
- Are there missing key terms?
- Are the key terms explained well?

**Sources**
- Are the sources mentioned?
- Are the mentioned sources correct?

**Excercise**
(Where applicable)
- Is the result correct?
- Are the experienced problems and solutions described well?
```

Share the link to this issue with your peers.

**Comment by jairvaneer** [comment]
**Summary**
- Does the summary describe the subject matter fully?
- Yes
- Is the summary written in own words?
- Yes
- Is there crucial information missing in the summary?
- No
- Is the description clear enough?
- Yes

**Key Terminology**
- Are there missing key terms?
- No
- Are the key terms explained well?
- Yes

**Sources**
- Are the sources mentioned?
- Yes
- Are the mentioned sources correct?
- Yes

**Excercise**
(Where applicable)
- Is the result correct?
- Yes
- Are the experienced problems and solutions described well?
- Yes

**Comment by yourlocaldaphne** [comment]
**Summary**
- Does the summary describe the subject matter fully?
Yes
- Is the summary written in own words?
Yes
- Is there crucial information missing in the summary?
No
- Is the description clear enough?
Yes

**Key Terminology**
- Are there missing key terms?
No
- Are the key terms explained well?
Yes

**Sources**
- Are the sources mentioned?
Yes
- Are the mentioned sources correct?
Yes

**Excercise**
(Where applicable)
- Is the result correct?
Yes
- Are the experienced problems and solutions described well?
Yes
